version: 2
jobs:
  build:
    docker:
      - image: cimg/openjdk:15.0.1
    steps:
      - checkout
      - run:
          command: find . -name 'pom.xml' | sort | xargs cat > /tmp/maven_cache_seed
          working_directory: $CIRCLE_WORKING_DIRECTORY/my-app
      - restore_cache:
          key: circleci-java-maven-{{ checksum "/tmp/maven_cache_seed" }}
      - run: 
          command: mvn dependency:go-offline
          working_directory: $CIRCLE_WORKING_DIRECTORY/my-app
      - run: 
          command: mvn package
          working_directory: $CIRCLE_WORKING_DIRECTORY/my-app          
      - save_cache:
          paths:
            - ~/.m2/repository
          key: circleci-java-maven-{{ checksum "/tmp/maven_cache_seed" }}
      - store_test_results:
          path: $CIRCLE_WORKING_DIRECTORY/my-app/target/surefire-reports
      - store_artifacts:
          path: $CIRCLE_WORKING_DIRECTORY/my-app/target/my-app-1.0-SNAPSHOT.jar