version: 2
jobs:
  build:
    working_directory: my-app
    docker:
      - image: cimg/openjdk:15.0.1
    steps:
      - checkout
      - restore_cache:
          key: circleci-java-maven-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: circleci-java-maven-{{ checksum "pom.xml" }}
      - run: mvn package
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/my-app-1.0-SNAPSHOT.jar